export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$HOME/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
eval "$(dircolors ~/.dircolors)"
# You can use whatever you want as an alias, like for Mondays:
# eval $(thefuck --alias FUCK)
