export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export JIRA_URL="https://jira.nl.flowtraders.local/"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

whiz()
{
    http --session whispers --body --timeout 900 http://whisperer/api/v1/"$@"
}

eval $(thefuck --alias fuck)
# You can use whatever you want as an alias, like for Mondays:
# eval $(thefuck --alias FUCK)
